---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/rscipher001/niri
name: niri
description: A minimal and functional silverblue based image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest

modules:
  - type: dnf
    install:
      install-weak-deps: true
      packages:
        - powertop
        - virt-manager
        - tlp

  - type: kargs
    kargs:
      - amdgpu.abmlevel=0

  - type: signing
