---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri
description: Niri and quickshell.

base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: 43 # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    repos:
      copr:
        - errornointernet/quickshell
    install:
      packages:
        - niri
        - quickshell
    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully
