---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/rscipher001/silverblue
name: silverblue
description: A functional silverblue image
base-image: ghcr.io/blue-build/base-images/fedora-silverblue-nvidia-open
image-version: latest

modules:
  - type: dnf
    repos:
      copr:
        - errornointernet/quickshell
    install:
      install-weak-deps: true
      packages:
        - virt-manager

     - type: signing
