---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: niri
description: Niri and quickshell.

base-image: ghcr.io/blue-build/base-images/fedora-base-nvidia-open
image-version: 43 # latest is also supported if you want new updates ASAP

modules:
  - type: dnf
    repos:
      copr:
        - errornointernet/quickshell
    install:
      install-weak-deps: true
      packages:
        - sddm
        - niri
        - nautilus
        - quickshell
        - virt-manager
        - brightnessctl
        - wlsunset
        - xdg-desktop-portal-gnome

    remove:
      packages:
        - firefox
        - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: signing
